# Generated by Django 3.2.9 on 2021-11-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
    ]
