# Generated by Django 3.2.9 on 2021-11-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
