# Generated by Django 3.2.9 on 2021-12-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0002_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='category_offer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
