# Generated by Django 3.2.9 on 2021-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0003_categoryoffer_category_offer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_offer_name', models.CharField(max_length=100, null=True)),
                ('offer_percent', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
    ]
