# Generated by Django 3.2.9 on 2021-12-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0004_auto_20211202_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='category_offer_name',
            new_name='offer_name',
        ),
    ]
