# Generated by Django 3.2.9 on 2021-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0006_auto_20211202_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_status',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
