# Generated by Django 3.2.9 on 2021-12-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0008_offer_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer_status',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
