# Generated by Django 3.2.9 on 2021-11-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorymanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('mrp', models.FloatField()),
                ('sale_price', models.TextField()),
                ('image', models.ImageField(upload_to='photos/products')),
                ('stocks', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('sub_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categorymanagement.subcategory')),
            ],
        ),
    ]
