# Generated by Django 3.2.9 on 2021-11-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0002_auto_20211111_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
