# Generated by Django 3.2.9 on 2021-11-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0003_auto_20211111_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_cover',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
