# Generated by Django 3.2.9 on 2021-11-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0004_products_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sale_price',
            field=models.IntegerField(),
        ),
    ]
