# Generated by Django 3.2.9 on 2021-12-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0011_products_offer_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer_status',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
