# Generated by Django 3.2.9 on 2021-12-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0012_alter_products_offer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(max_length=50, unique=True)),
                ('coupon_name', models.CharField(max_length=50, unique=True)),
                ('coupon_percent', models.IntegerField()),
                ('coupon_status', models.BooleanField(default=False)),
            ],
        ),
    ]
