# Generated by Django 3.2.9 on 2021-12-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0013_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
