# Generated by Django 3.2.9 on 2021-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0014_coupon_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_time',
            field=models.TimeField(null=True),
        ),
    ]
