# Generated by Django 3.2.9 on 2021-12-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0008_offer_expiry_time'),
        ('productmanagement', '0016_expiredcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorymanagement.category'),
        ),
    ]
