# Generated by Django 3.2.9 on 2021-11-18 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productmanagement', '0004_products_product_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanagement.products')),
            ],
        ),
    ]
