# Generated by Django 3.2.9 on 2021-11-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
