# Generated by Django 3.2.9 on 2021-12-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
