# Generated by Django 3.2.9 on 2021-12-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20211209_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
