# Generated by Django 3.2.9 on 2021-12-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cartitems_buy_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='buy_now',
        ),
    ]
