# Generated by Django 3.2.9 on 2021-11-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
