# Generated by Django 3.2.9 on 2021-12-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='wallet_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
