# Generated by Django 3.2.9 on 2021-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_accounts_wallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='refereral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
